root: true

env:
  browser: true
  es6: true
  webextensions: true

extends:
  eslint:recommended

globals:
  $: false
  $1: false
  bg: false
  cleanUrl: false

parserOptions:
  ecmaVersion: 8

rules:
  no-console: 1
  no-undef: 1
  no-unused-vars: 1
  prefer-arrow-callback: 1
  prefer-const: 1
